# Generated by Django 4.2.15 on 2025-03-28 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("embedding", "0003_alter_embedding_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="embedding",
            name="chunk_data",
            field=models.CharField(default="", max_length=1024, verbose_name="分块数据"),
        ),
    ]
