# Generated by Django 4.2.15 on 2025-03-31 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dataset", "0014_alter_document_status_alter_paragraph_status_chunk"),
        ("embedding", "0004_embedding_chunk_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="embedding",
            name="chunk_data",
        ),
        migrations.AddField(
            model_name="embedding",
            name="chunk",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="dataset.chunk",
                verbose_name="分块关联",
            ),
        ),
    ]
