# Generated by Django 4.2.15 on 2025-03-03 09:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_user_language"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSetting",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid1,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="主键id",
                    ),
                ),
                (
                    "user_id",
                    models.UUIDField(
                        default=uuid.uuid1, editable=False, verbose_name="用户id"
                    ),
                ),
                ("setting_type", models.CharField(max_length=50, verbose_name="设置类型")),
                ("name", models.CharField(max_length=100, verbose_name="名称")),
                ("value", models.CharField(max_length=150, verbose_name="值")),
                ("description", models.CharField(max_length=50, verbose_name="描述")),
                ("remark", models.CharField(max_length=50, verbose_name="备注")),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, null=True, verbose_name="修改时间"),
                ),
            ],
            options={
                "db_table": "user_setting",
            },
        ),
    ]
