# Generated by Django 4.2.15 on 2024-10-17 11:00

import uuid
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('setting', '0010_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False, verbose_name='主键id')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setting.group', verbose_name='分组id')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='用户id')),
            ],
            options={
                'db_table': 'group_member',
                'unique_together': {('user',)},
            },
        ),
    ] 