# Generated by Django 4.2.15 on 2024-10-17 11:30

import uuid
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('setting', '0011_groupmember'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupDetails',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False, verbose_name='主键id')),
                ('target_type', models.CharField(choices=[('APPLICATION', '应用'), ('DATASET', '数据集')], max_length=20, verbose_name='目标类型')),
                ('target_id', models.UUIDField(verbose_name='目标id')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setting.group', verbose_name='分组id')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='用户id')),
            ],
            options={
                'db_table': 'group_details',
                'unique_together': {('target_type', 'target_id')},
            },
        ),
    ] 