# Generated by Django 4.2.15 on 2025-04-03 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("setting", "0012_groupdetails"),
    ]

    operations = [
        migrations.AddField(
            model_name="model",
            name="http_header",
            field=models.JSONField(default=list, verbose_name="HTTP Header配置"),
        ),
    ]
