# Generated by Django 4.2.15 on 2025-04-09 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("setting", "0010_log"),
        ("setting", "0013_model_http_header"),
    ]

    operations = []
