# Generated by Django 4.2.15 on 2025-03-20 02:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    # dependencies = [
    #     ("function_lib", "0002_functionlib_is_active_functionlib_permission_type"),
    #     ("users", "0006_user_setting"),
    # ]

    operations = [
        migrations.CreateModel(
            name="ScheduleTask",
            fields=[
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="修改时间"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid1,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="主键id",
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="任务名称")),
                (
                    "desc",
                    models.CharField(
                        blank=True, max_length=128, null=True, verbose_name="描述"
                    ),
                ),
                (
                    "cron_expression",
                    models.CharField(max_length=64, verbose_name="cron表达式"),
                ),
                ("params", models.JSONField(default=dict, verbose_name="函数参数")),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                (
                    "function_lib",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="function_lib.functionlib",
                        verbose_name="关联函数",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.user",
                        verbose_name="创建用户",
                    ),
                ),
            ],
            options={
                "db_table": "schedule_task",
            },
        ),
    ]
