# Generated by Django 4.2.15 on 2025-03-24 01:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduleTaskRecord",
            fields=[
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="修改时间"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid1,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="主键id",
                    ),
                ),
                ("start_time", models.DateTimeField(verbose_name="开始时间")),
                (
                    "end_time",
                    models.DateTimeField(blank=True, null=True, verbose_name="结束时间"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUCCESS", "成功"),
                            ("FAILED", "失败"),
                            ("RUNNING", "执行中"),
                        ],
                        max_length=20,
                        verbose_name="执行状态",
                    ),
                ),
                (
                    "result",
                    models.TextField(blank=True, null=True, verbose_name="执行结果"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="错误信息"),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="schedule.scheduletask",
                        verbose_name="关联任务",
                    ),
                ),
            ],
            options={
                "db_table": "schedule_task_record",
            },
        ),
    ]
