# Generated by Django 4.2.15 on 2025-03-25 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("setting", "0012_groupdetails"),
        ("schedule", "0003_scheduletask_dataset"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduletask",
            name="model",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="setting.model",
                verbose_name="模型",
            ),
        ),
        migrations.AddField(
            model_name="scheduletask",
            name="prompt",
            field=models.TextField(blank=True, null=True, verbose_name="提示词"),
        ),
    ]
