# Generated by Django 4.2.15 on 2025-03-25 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0004_scheduletask_model_scheduletask_prompt"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduletask",
            name="retain_thinking",
            field=models.BooleanField(
                default=False,
                verbose_name="保留思考内容",
                help_text="是否保留模型的思考过程"
            ),
        ),
    ]
