# Generated by Django 4.2.15 on 2025-03-26 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0005_scheduletask_retain_thinking"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduletask",
            name="task_params",
            field=models.JSONField(
                default=dict,
                verbose_name="任务参数", 
                help_text="任务配置参数，如标题提示词等"
            ),
        ),
    ] 