# Generated by Django 4.2.15 on 2025-03-04 10:03

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0025_alter_application_prologue"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplicationSetting",
            fields=[
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="修改时间"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid1,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="主键id",
                    ),
                ),
                (
                    "show_history",
                    models.BooleanField(default=True, verbose_name="是否显示历史记录"),
                ),
                ("draggable", models.BooleanField(default=True, verbose_name="是否可拖拽")),
                (
                    "show_guide",
                    models.BooleanField(default=True, verbose_name="是否显示引导"),
                ),
                (
                    "avatar",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="AI头像"
                    ),
                ),
                (
                    "avatar_url",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="AI头像URL"
                    ),
                ),
                (
                    "float_icon",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="悬浮图标"
                    ),
                ),
                (
                    "float_icon_url",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="悬浮图标URL"
                    ),
                ),
                (
                    "user_avatar",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="用户头像"
                    ),
                ),
                (
                    "user_avatar_url",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="用户头像URL"
                    ),
                ),
                (
                    "disclaimer",
                    models.BooleanField(default=False, verbose_name="是否显示免责声明"),
                ),
                (
                    "disclaimer_value",
                    models.CharField(
                        blank=True, max_length=128, null=True, verbose_name="免责声明内容"
                    ),
                ),
                ("custom_theme", models.JSONField(default=dict, verbose_name="自定义主题")),
                ("float_location", models.JSONField(default=dict, verbose_name="悬浮位置")),
                (
                    "authentication",
                    models.BooleanField(default=False, verbose_name="是否鉴权"),
                ),
                (
                    "authentication_value",
                    models.JSONField(default=dict, verbose_name="鉴权内容"),
                ),
                (
                    "access_token",
                    models.CharField(
                        default=uuid.uuid1, max_length=128, unique=True, verbose_name="用户公开访问 认证token"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否开启公开访问"),
                ),
                ("access_num", models.IntegerField(default=100, verbose_name="访问次数")),
                (
                    "white_active",
                    models.BooleanField(default=False, verbose_name="是否开启白名单"),
                ),
                (
                    "white_list",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(blank=True, max_length=128),
                        default=list,
                        size=None,
                        verbose_name="白名单列表",
                    ),
                ),
                (
                    "show_source",
                    models.BooleanField(default=False, verbose_name="是否显示知识来源"),
                ),
                (
                    "language",
                    models.CharField(
                        default=None, max_length=10, null=True, verbose_name="语言"
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="application.application",
                        verbose_name="应用id",
                    ),
                ),
            ],
            options={
                "db_table": "application_setting",
            },
        ),
    ]
