# Generated by Django 4.2.15 on 2025-04-03 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0026_applicationi_setting"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationapikey",
            name="name",
            field=models.CharField(default="", max_length=128, verbose_name="名称"),
        ),
        migrations.AlterField(
            model_name="applicationsetting",
            name="access_token",
            field=models.CharField(
                max_length=128, unique=True, verbose_name="用户公开访问 认证token"
            ),
        ),
    ]
