# Generated by Django 4.2.15 on 2025-04-09 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0026_chat_asker"),
        ("application", "0028_chat_api_key"),
    ]

    operations = []
