# Generated by Django 4.2.15 on 2025-04-09 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0029_merge_0026_chat_asker_0028_chat_api_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationsetting",
            name="show_avatar",
            field=models.BooleanField(default=True, verbose_name="是否显示头像"),
        ),
    ]
