# Generated by Django 4.2.15 on 2025-04-09 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0030_applicationsetting_show_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicationsetting",
            name="show_user_avatar",
            field=models.BooleanField(default=True, verbose_name="是否显示用户头像"),
        ),
    ]
